### ISSUE TITLE
Add upgradeablity proxy(?)

### ISSUE THREAD

**Issue by kadenzipfel** [PaulRBerg/cea-template#10]
As per: https://docs.openzeppelin.com/upgrades/2.6/proxies

I think this would be a real game-changer, what do you think?

**Comment by PaulRBerg** [comment]
Well, after the recent push towards [Experience Architects](https://github.com/PaulRBerg/create-eth-app#philosophy), I don't see upgradeable proxies as part of the immediate roadmap. This is because we're providing a smart contract development environment, by default.

Users are of course to drop their own truffle project as a package. Maybe we could add the ability to use other templates in the future? Create Next App has a cool `--with-example` option that offers this functionality.

**Comment by PaulRBerg** [comment]
Closing this temporarily.
